name: Build APK
on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # Usamos un contenedor que ya tiene TODO instalado (Android SDK, NDK, dependencias...)
    container:
      image: kivy/buildozer:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name:       - name: Build with Buildozer
        run: |
          # Intentamos la compilación con logs detallados
          buildozer -v android debug || (tail -n 100 buildozer.log && exit 1)

        run: |
          # Damos permisos al usuario para que pueda trabajar dentro del contenedor
          chown -R user .
          # Ejecutamos la compilación
          yes | buildozer -v android debug
        
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Chito-APK
          path: bin/*.apk
