name: Build APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build with Buildozer (Docker Directo)
        run: |
          # Usamos la imagen oficial de Kivy para compilar
          docker run --rm \
            -v "$(pwd)":/home/buildozer/host \
            -v "$(pwd)"/.buildozer:/home/buildozer/.buildozer \
            kivy/buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Chito-APK
          path: bin/*.apk
